version: '3'

services:
  tortoisebot-ros2-real:
    image: hamz115/hamzaferoze-cp22:ros2-real
    container_name: tortoisebot-ros2-real
    privileged: true
    volumes:
      - /dev/mem:/dev/mem
      - /dev/vchiq:/dev/vchiq
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/dri:/dev/dri
      - $HOME/.Xauthority:/root/.Xauthority
    network_mode: "host"
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - ROS_DOMAIN_ID=42
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp

  tortoisebot-ros2-slam-real:
    image: hamz115/hamzaferoze-cp22:ros2-slam-real
    container_name: tortoisebot-ros2-slam-real
    privileged: true
    volumes:
      - /dev/mem:/dev/mem
      - /dev/vchiq:/dev/vchiq
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/dri:/dev/dri
      - $HOME/.Xauthority:/root/.Xauthority
    network_mode: "host"
    environment:
      - DISPLAY
      - ROS_DOMAIN_ID=42
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - QT_X11_NO_MITSHM=1

  